project_id = "pnkhogpsadywdbgzqhfi"

[functions.generate-medical-record]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.expire-trials]
verify_jwt = false
