-- Expansão da ficha de cadastro do paciente
ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS social_name text,
  ADD COLUMN IF NOT EXISTS birth_place text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS rg_issuer text,
  ADD COLUMN IF NOT EXISTS cnh text,
  ADD COLUMN IF NOT EXISTS phone_residential text,
  ADD COLUMN IF NOT EXISTS education_level text,
  ADD COLUMN IF NOT EXISTS profession_role text,
  ADD COLUMN IF NOT EXISTS spouse_name text,
  ADD COLUMN IF NOT EXISTS spouse_relationship_time text,
  ADD COLUMN IF NOT EXISTS children jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS father_profession text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS mother_profession text,
  ADD COLUMN IF NOT EXISTS siblings_brothers integer,
  ADD COLUMN IF NOT EXISTS siblings_sisters integer,
  ADD COLUMN IF NOT EXISTS emergency_whatsapp text,
  ADD COLUMN IF NOT EXISTS prior_therapy boolean,
  ADD COLUMN IF NOT EXISTS prior_therapy_duration text,
  ADD COLUMN IF NOT EXISTS prior_therapy_when text,
  ADD COLUMN IF NOT EXISTS prior_therapy_reason text,
  ADD COLUMN IF NOT EXISTS uses_medication boolean,
  ADD COLUMN IF NOT EXISTS medications jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS initial_demand text,
  ADD COLUMN IF NOT EXISTS lgpd_truth_declaration boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS lgpd_privacy_consent boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS lgpd_data_consent boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS recording_authorization text,
  ADD COLUMN IF NOT EXISTS signature_ip text,
  ADD COLUMN IF NOT EXISTS signature_device text,
  ADD COLUMN IF NOT EXISTS signature_timestamp timestamptz;